[package]
name = "asphaleia-net"
version = "0.0.1"
edition = "2021"

[dependencies]
bytes = "1.7.1"
quinn = "0.11.3"
asphaleia-crypto = { path = "../asphaleia-crypto" }
tokio = { version = "1.39.3", features = ["macros"] }
tokio-macros = "2.4.0"

[dev-dependencies]
better-panic = "0.3.0"
